#
# Lethean Binary API
# Functionality to simplify using LTHN
# Version: 1.2.2
# Contact: contact@lethean.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'letheanSDP' -name 'letheanSDPLetheanSDPVpnApi' {
    Context 'Start-letheanSDPLetheand' {
        It 'Test Start-letheanSDPLetheand' {
            #$TestResult = Start-letheanSDPLetheand -DataDir "TEST_VALUE" -Version "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
